Touchups.

diff --git a/sh/install/_ b/sh/install/_
--- a/sh/install/_
+++ b/sh/install/_
@@ -2,6 +2,7 @@
 #
 
 # === {{CMD}}  # Installs Crystal to /tmp
+# === Installs Crystal version specified in configs/crystal-version
 
 get-output () {
   "$@" 2>/dev/null || :
@@ -20,38 +21,27 @@ case "$(lsb_release -r -c -s)" in
     ;;
 esac
 
-local +x NAME="Crystal"
-local +x URL="https://github.com/crystal-lang/crystal/releases"
-
-local +x STORAGE="$THIS_DIR/tmp/crystal"
-local +x LATEST="$(my_crystal latest)"
-local +x CURRENT="$(my_crystal current)"
-local +x BASENAME="$(basename "$LATEST")"
-local +x VERSION="$(basename "$LATEST" .tar.gz)"
+local +x VERSION="$(my_crystal current)"
 local +x DIR="$THIS_DIR/tmp/crystal-versions/$VERSION"
 local +x LATEST_LINK="$THIS_DIR/tmp/latest-crystal"
+local +x CRYSTAL="$LATEST_LINK/bin/crystal"
 
-if [[ -z "$LATEST" ]]; then
-  echo "!!! Could not determine latest $NAME download on the Internet." >&2
-  exit 2
+if [[ -z "$VERSION" ]]; then
+  echo "!!! Could not determine latest Crystal download on the Internet." >&2
+  exit 1
 fi
 
-local +x CRYSTAL="$LATEST_LINK/bin/crystal"
-if [[ -x "$CRYSTAL" ]]; then
-  local +x LATEST_VERSION="$(get-output "$CRYSTAL" --version)"
-
-  if [[ ! -z "$LATEST_VERSION" && "$LATEST_VERSION" == "$(get-output "$DIR"/bin/crystal --version)" ]]; then
-    echo "=== Already installed latest $NAME:" >&2
-    echo "$DIR" >&2
-    "$LATEST_LINK"/bin/crystal --version >&2
-    return 0
-  fi
+if [[ "$(realpath "$LATEST_LINK")" == "$(realpath "$DIR")"  && -x "$CRYSTAL" ]]; then
+  echo "=== Already installed: " >&2
+  echo "$VERSION" >&2
+  my_crystal --version
+  return 0
 fi
 
 mkdir -p "$(dirname "$DIR")"
 mkdir -p "$THIS_DIR/tmp"
 
-local +x TMP_FILE="$(my_crystal download)"
+local +x TMP_FILE="$(my_crystal download $VERSION)"
 if [[ -z "$TMP_FILE" ]]; then
   exit 5
 fi
@@ -65,6 +55,6 @@ ln -s "$DIR" "$LATEST_LINK"
 
 echo "$LATEST" > "$CRYSTAL_VERSION_FILE"
 echo "=== Installed Crystal:" >&2
-"$LATEST_LINK"/bin/crystal --version >&2
+"$CRYSTAL" --version
 
 
